version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/packages/grafana-llm-app"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
